version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    restart: always

  chrome:
    image: selenium/node-chrome:3.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    restart: always
